name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      IS_CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.8'
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install torch-scatter -f https://data.pyg.org/whl/torch-2.4.0+cpu.html
          pip install torch-cluster -f https://data.pyg.org/whl/torch-2.4.0+cpu.html
      - name: Run tests
        run: |
          cd omat24
          pytest tests/test_transformer.py
          pytest tests/test_dataloader.py
          pytest tests/test_fcn.py
          pytest tests/test_equiformer_v2.py
          pytest tests/test_collect_samples_for_visualizing.py
